version: '2'

includes:
    _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
    PATH: "github.com/3vilcookie/copilot"
    BINARY_NAME: copilot
    REPOSITORY_NAME: "3vilcookie/copilot"

