version: '2'

includes:
    _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
    PATH: "github.com/3vilcookie/prettybool"
    BINARY_NAME: prettybool
    REPOSITORY_NAME: "3vilcookie/prettybool"

