version: '2'

includes:
    _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
    PATH: "github.com/3vilcookie/sembool"
    BINARY_NAME: sembool
    REPOSITORY_NAME: "3vilcookie/sembool"

