version: '2'

includes:
    _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
    PATH: "github.com/RaphaelPour/prettybool"
    BINARY_NAME: prettybool
    REPOSITORY_NAME: "RaphaelPour/prettybool"

tasks:
  bin:
    desc: Build the go binary
    cmds:
      - cd cmd && go build -a -ldflags "-X {{.PATH}}/cmd.BuildDate={{.DATE}} -X {{.PATH}}/cmd.BuildVersion={{.VERSION}} -extldflags '-static' -s -w" -o ../ci-build/{{.BINARY_NAME}}
    vars:
      DATE:
        sh: date '+%Y-%m-%dT%H:%M:%S%z'
      VERSION:
        sh: git describe --tags || git describe --always   
